In [25]:
import pandas as pd
import torch as t
import numpy as np

# LM-37 bacteria

In [6]:
df = pd.read_csv(
    "bacteria-37.csv",
    header=1,
    usecols= [
        "Position X",
        "Position Y",
        "Position Z",
        "Time",
        "TrackID",
        "ID"
    ]
)

In [11]:
display(df.head())
df.info()

Position X  Position Y  Position Z  Time     TrackID  ID
0    248.6320     10.7085      0.1815     1  1000000008   8
1    346.6570     10.7085      0.1815     1  1000000014  14
2     52.1679     11.1991      0.1815     1  1000000015  15
3     32.9705     11.6746      0.1815     1  1000000018  18
4    272.7170     11.8309      0.1815     1  1000000020  20

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17822 entries, 0 to 17821
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Position X  17822 non-null  float64
 1   Position Y  17822 non-null  float64
 2   Position Z  17822 non-null  float64
 3   Time        17822 non-null  int64  
 4   TrackID     17822 non-null  int64  
 5   ID          17822 non-null  int64  
dtypes: float64(3), int64(3)
memory usage: 835.5 KB


In [13]:
pd.unique(df["TrackID"]).shape

(299,)

In [28]:
(df[df["TrackID"] == 1000000015]).sort_values(by="Time")

Position X  Position Y  Position Z  Time     TrackID     ID
2         52.1679     11.1991      0.1815     1  1000000015     15
298       52.1539     11.2009      0.1815     2  1000000015   1557
595       52.1554     11.2338      0.1815     3  1000000015   3272
893       52.2164     11.2702      0.1815     4  1000000015   4848
1191      52.1607     11.2256      0.1815     5  1000000015   6400
1489      52.2040     11.2801      0.1815     6  1000000015   8034
1787      52.1384     11.2526      0.1815     7  1000000015   9610
2085      52.2176     11.2861      0.1815     8  1000000015  11335
2383      52.1484     11.2188      0.1815     9  1000000015  13067
2680      52.1507     11.1809      0.1815    10  1000000015  14778
2977      52.1387     11.1326      0.1815    11  1000000015  16485
3274      52.1539     11.1120      0.1815    12  1000000015  18046
3571      52.1274     11.1628      0.1815    13  1000000015  19747
3868      52.1302     11.1801      0.1815    14  1000000015  21242
4165      52.1216     11.1595      0.1815    15  1000000015  22916
4462      52.1273     11.1654      0.1815    16  1000000015  24453
4759      52.1422     11.1460      0.1815    17  1000000015  26163
5056      52.1371     11.1218      0.1815    18  1000000015  27686
5353      52.1313     11.1376      0.1815    19  1000000015  29234
5650      52.1483     11.0610      0.1815    20  1000000015  30764
5947      52.1252     11.1314      0.1815    21  1000000015  32308
6244      52.1287     11.1301      0.1815    22  1000000015  33830
6541      52.1495     11.1346      0.1815    23  1000000015  35353
6838      52.1207     11.1845      0.1815    24  1000000015  36874
7135      52.1368     11.1084      0.1815    25  1000000015  38384
7432      52.1588     11.1791      0.1815    26  1000000015  39908
7729      52.1426     11.1538      0.1815    27  1000000015  41424
8026      52.1395     11.1823      0.1815    28  1000000015  42955
8323      52.1403     11.1592      0.1815    29  1000000015  44496
8620      52.1332     11.1446      0.1815    30  1000000015  46007
8917      52.1249     11.1267      0.1815    31  1000000015  47537
9214      52.1327     11.1370      0.1815    32  1000000015  49065
9511      52.1261     11.2009      0.1815    33  1000000015  50590
9808      52.1417     11.1711      0.1815    34  1000000015  52094
10105     52.1756     11.1993      0.1815    35  1000000015  53594
10402     52.1313     11.1206      0.1815    36  1000000015  55128
10699     52.1451     11.1444      0.1815    37  1000000015  56622
10995     52.1433     11.1834      0.1815    38  1000000015  58167
11291     52.1419     11.2047      0.1815    39  1000000015  59710
11587     52.1546     11.1881      0.1815    40  1000000015  61275
11884     52.1287     11.1367      0.1815    41  1000000015  62796
12181     52.1205     11.1884      0.1815    42  1000000015  64561
12478     52.1441     11.1966      0.1815    43  1000000015  66265
12775     52.1301     11.1363      0.1815    44  1000000015  67792
13072     52.1242     11.1657      0.1815    45  1000000015  69321
13369     52.1250     11.1735      0.1815    46  1000000015  70860
13666     52.1293     11.1799      0.1815    47  1000000015  72573
13963     52.1437     11.2022      0.1815    48  1000000015  74127
14260     52.1493     11.1221      0.1815    49  1000000015  75845
14557     52.1500     11.2163      0.1815    50  1000000015  77349
14854     52.1361     11.2194      0.1815    51  1000000015  78830
15151     52.1487     11.1685      0.1815    52  1000000015  80317
15448     52.1231     11.1972      0.1815    53  1000000015  81980
15745     52.1087     11.1474      0.1815    54  1000000015  83494
16042     52.1148     11.1655      0.1815    55  1000000015  84985
16339     52.1231     11.1576      0.1815    56  1000000015  86503
16636     52.1431     11.1133      0.1815    57  1000000015  88057
16933     52.1255     11.1351      0.1815    58  1000000015  89560
17230     52.1394     11.1357      0.1815    59  10000

In [26]:
np.unique(df["Time"].to_numpy(), return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int64),
 array([296, 297, 298, 298, 298, 298, 298, 298, 297, 297, 297, 297, 297,
        297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297,
        297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 296, 296, 296,
        297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297, 297,
        297, 297, 297, 297, 297, 297, 297, 297], dtype=int64))

In [32]:
tracks = pd.unique(df["TrackID"])

x_fluctuations = []
y_fluctuations = []
for track_id in tracks:
    pos_x = df[df["TrackID"] == track_id]["Position X"]
    pos_y = df[df["TrackID"] == track_id]["Position Y"]
    x_fluctuations.append(pos_x.max() - pos_x.min())
    y_fluctuations.append(pos_y.max() - pos_y.min())
print(f"min. x fluctuation: {np.min(x_fluctuations)}, max. x fluctuation: {np.max(x_fluctuations)}, avg. x fluctuation: {np.mean(x_fluctuations)}")
print(f"min. y fluctuation: {np.min(y_fluctuations)}, max. y fluctuation: {np.max(y_fluctuations)}, avg. y fluctuation: {np.mean(y_fluctuations)}")    

min. x fluctuation: 0.0, max. x fluctuation: 0.8780000000000143, avg. x fluctuation: 0.06948056856187337
min. y fluctuation: 0.0, max. y fluctuation: 0.30449999999999733, avg. y fluctuation: 0.06715183946488228


# LM-RT bacteria

In [36]:
df_rt = pd.read_csv(
    "bacteria-RT.csv",
    header=1,
    usecols= [
        "Position X",
        "Position Y",
        "Position Z",
        "Time",
        "TrackID",
        "ID"
    ]
)

In [37]:
display(df_rt.head())
df_rt.info()

Position X  Position Y  Position Z  Time     TrackID  ID
0     295.338     258.637      0.1815     1  1000000007   7
1     422.484     258.637      0.1815     1  1000000014  14
2     468.483     258.637      0.1815     1  1000000016  16
3     362.448     259.978      0.1815     1  1000000025  25
4     470.481     261.132      0.1815     1  1000000029  29

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29493 entries, 0 to 29492
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Position X  29493 non-null  float64
 1   Position Y  29493 non-null  float64
 2   Position Z  29493 non-null  float64
 3   Time        29493 non-null  int64  
 4   TrackID     29493 non-null  int64  
 5   ID          29493 non-null  int64  
dtypes: float64(3), int64(3)
memory usage: 1.4 MB


In [38]:
np.unique(df_rt["Time"].to_numpy(), return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int64),
 array([472, 479, 488, 491, 488, 490, 493, 494, 494, 498, 496, 490, 488,
        486, 488, 486, 491, 492, 495, 496, 498, 495, 489, 493, 491, 491,
        485, 486, 488, 495, 491, 501, 495, 497, 496, 497, 497, 494, 493,
        491, 496, 494, 498, 500, 498, 502, 499, 498, 492, 490, 488, 493,
        489, 494, 491, 495, 496, 483, 476, 463], dtype=int64))

In [41]:
tracks = pd.unique(df_rt["TrackID"])

x_fluctuations = []
y_fluctuations = []
for track_id in tracks:
    pos_x = df_rt[df_rt["TrackID"] == track_id]["Position X"]
    pos_y = df_rt[df_rt["TrackID"] == track_id]["Position Y"]
    x_fluctuations.append(pos_x.max() - pos_x.min())
    y_fluctuations.append(pos_y.max() - pos_y.min())
print(f"min. x fluctuation: {np.min(x_fluctuations)}, max. x fluctuation: {np.max(x_fluctuations)}, avg. x fluctuation: {np.mean(x_fluctuations)}")
print(f"min. y fluctuation: {np.min(y_fluctuations)}, max. y fluctuation: {np.max(y_fluctuations)}, avg. y fluctuation: {np.mean(y_fluctuations)}")    

min. x fluctuation: 0.0, max. x fluctuation: 133.238, avg. x fluctuation: 15.301285886610373
min. y fluctuation: 0.0, max. y fluctuation: 205.789, avg. y fluctuation: 15.736419782870927


# Bacterial CPM

- either 1 or 2 pixels (2-4 $\mu m$) -> 1 cell is 2 Microns, the unit in the df for positions is Microns
- 