In [1]:
import torch as t
import sys
sys.path.append("../../")
from hamiltonian_diff import model
from cell_typing import CellKind, CellMap

In [2]:
grid = t.zeros((1,5,5))
grid[0,1,2] = 1
grid[0,2,1] = 1
grid[0,2,2] = 1
grid[0,2,3] = 1
grid[0,3,2] = 1
print(grid)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 1., 1., 1., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0.]]])


In [3]:
target_perim1 = t.tensor(10.)
lambda_perim1 = t.tensor(1.)
target_vol1 = t.tensor(7.)
lambda_vol1 = t.tensor(1.)
adh_cost1 = {0: 2.}
cell1 = CellKind(
    type_id=1,
    target_perimeter=target_perim1,
    lambda_perimeter=lambda_perim1,
    target_volume=target_vol1,
    lambda_volume=lambda_vol1,
    adhesion_cost=adh_cost1
)
cell_map = CellMap()
cell_map.add(cell_id=1, cell_type=cell1)

temperature = t.tensor(27.)

In [13]:
grid, stats = model(grid, cell_map, temperature)

In [14]:
print(stats["src_pixel"])
print(stats["target_pixel"])
print(stats["current"])
print(stats["adjusted"])
print(stats["h_diff"])
print(stats["p_copy"])
print(stats["success"])
print(grid)

[[0 2 0]]
[[0 2 1]]
{'volume_energy': tensor([9.]), 'perimeter_energy': tensor([144.]), 'adh_e': tensor([44.]), 'h': tensor([197.])}
{'volume_energy': tensor([16.]), 'perimeter_energy': tensor([100.]), 'adh_e': tensor([40.]), 'h': tensor([156.])}
tensor([-41.])
tensor([4.5655])
tensor(1.)
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0.]]])
