In [1]:
import torch as t
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append("../../")
from periodic_padding import periodic_padding
from hamiltonian_diff import model
from cell_typing import CellKind, CellMap

In [13]:
unfold_transform = t.nn.Unfold(kernel_size=4)

test = t.arange(64.).reshape(1,8,8)
test = periodic_padding(test)
test = test.unsqueeze(1)
print(test)
print(unfold_transform(test).shape)

unfolded = unfold_transform(test).squeeze(0).T

tensor([[[[63., 56., 57., 58., 59., 60., 61., 62., 63., 56.],
          [ 7.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  0.],
          [15.,  8.,  9., 10., 11., 12., 13., 14., 15.,  8.],
          [23., 16., 17., 18., 19., 20., 21., 22., 23., 16.],
          [31., 24., 25., 26., 27., 28., 29., 30., 31., 24.],
          [39., 32., 33., 34., 35., 36., 37., 38., 39., 32.],
          [47., 40., 41., 42., 43., 44., 45., 46., 47., 40.],
          [55., 48., 49., 50., 51., 52., 53., 54., 55., 48.],
          [63., 56., 57., 58., 59., 60., 61., 62., 63., 56.],
          [ 7.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  0.]]]])
torch.Size([1, 16, 49])


In [6]:
unfolded[0]

tensor([63., 56., 57., 58.,  7.,  0.,  1.,  2., 15.,  8.,  9., 10., 23., 16.,
        17., 18.])

In [12]:
unfold_transform = t.nn.Unfold(kernel_size=4)

test = t.arange(128.).reshape(2,8,8)
test = periodic_padding(test)
test = test.unsqueeze(1)
print(test)
print(unfold_transform(test).shape)
unfolded = t.transpose(unfold_transform(test), dim0=1, dim1=2)

tensor([[[[ 63.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  56.],
          [  7.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   0.],
          [ 15.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,   8.],
          [ 23.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  16.],
          [ 31.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  24.],
          [ 39.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  32.],
          [ 47.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  40.],
          [ 55.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  48.],
          [ 63.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  56.],
          [  7.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   0.]]],


        [[[127., 120., 121., 122., 123., 124., 125., 126., 127., 120.],
          [ 71.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  64.],
          [ 79.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  72.],
          [ 87.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  

In [10]:
unfolded.shape

torch.Size([2, 49, 16])